### ISSUE TITLE
Unable to extract login-form form

### ISSUE THREAD

**Issue by Niko7700** [r0oth3x49/udemy-dl#102]
Hi,

I try to download a course, but it shows me the following
---------------------------------------------------------------
[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'proyecto ecommerce java ee jsp servlet con pagos en linea'.
[*] : Trying to login as (nicoyani8@gmail.com)...
[-] Unable to extract login-form form
Traceback (most recent call last):
  File "D:/utils/udemy/udemy-dl-master/udemy-dl.py", line 924, in <module>
    main()
  File "D:/utils/udemy/udemy-dl-master/udemy-dl.py", line 829, in main
    udemy.ExtractAndDownload()
  File "D:/utils/udemy/udemy-dl-master/udemy-dl.py", line 291, in ExtractAndDownload
    self.login()
  File "D:/utils/udemy/udemy-dl-master/udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "D:\utils\udemy\udemy-dl-master\udemy\_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "D:\utils\udemy\udemy-dl-master\udemy\_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "D:\utils\udemy\udemy-dl-master\udemy\_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "D:\utils\udemy\udemy-dl-master\udemy\_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'', '', html)
  File "C:\Program Files (x86)\Python36-32\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

------------------------
thanks for your help

**Comment by linneudm** [comment]
@Niko7700 check issue #98 the owner have already discussed the solution to this.

**Comment by r0oth3x49** [comment]
@linneudm thank you for your support. @Niko7700 i 'm closing this issue as duplicate you can check the solution in an issue link given by @linneudm .
