### ISSUE TITLE
Windows: Unable to extract login-form form

### ISSUE THREAD

**Issue by Darking360** [r0oth3x49/udemy-dl#103]
I'm trying to download from Udemy as explained in README.md. But when I try to run udemy-dl.py, I put my email and password, then it says that is extracting course information, then trying to login (I already checked that my credentials are ok), after that, it says:

`[-] Unable to extract login-form form
Traceback (most recent call last):
  File ".\udemy-dl.py", line 924, in <module>
    main()
  File ".\udemy-dl.py", line 713, in main
    udemy.ExtractAndDownload()
  File ".\udemy-dl.py", line 291, in ExtractAndDownload
    self.login()
  File ".\udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "C:\Users\Miguel Bolivar\Downloads\udemy-dl-master\udemy-dl-master\udemy\_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "C:\Users\Miguel Bolivar\Downloads\udemy-dl-master\udemy-dl-master\udemy\_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "C:\Users\Miguel Bolivar\Downloads\udemy-dl-master\udemy-dl-master\udemy\_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "C:\Users\Miguel Bolivar\Downloads\udemy-dl-master\udemy-dl-master\udemy\_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'', '', html)
  File "C:\Users\Miguel Bolivar\AppData\Local\Programs\Python\Python36\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object`

I'm using Windows 10 and Python 3.6.4. I don't know what could be the issue.

**Comment by r0oth3x49** [comment]
@Darking360 you should check #98 and #100 . already discussed there.
