### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by valix85** [r0oth3x49/udemy-dl#104]
Hi I'm trying to login/download and every time obtain this error:

> >python udemy-dl.py https://www.udemy.com/java-course-fundamentals/learn/v4/overview

`
[-] Unable to extract login-form form
Traceback (most recent call last):
  File "udemy-dl.py", line 936, in <module>
    main()
  File "udemy-dl.py", line 725, in main
    udemy.ExtractAndDownload()
  File "udemy-dl.py", line 303, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "C:\Programmi Portable\udemy-dl\udemy\_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "C:\Programmi Portable\udemy-dl\udemy\_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "C:\Programmi Portable\udemy-dl\udemy\_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "C:\Programmi Portable\udemy-dl\udemy\_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'', '', html)
  File "C:\Program Files\Python36\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
`

Can you fix it please?
thank you

**Comment by Niko7700** [comment]
you should check #98 issue.

**Comment by r0oth3x49** [comment]
@Niko7700 thanks for your support. @valix85 check the solution. i 'm closing this issue as duplicate

**Comment by valix85** [comment]
Perfect just try to update a package. execute: pip install requests[security] and all works fine. thank you

**Comment by helenyau0** [comment]
@r0oth3x49 when I try to run `pip install requests[security]` it gives me the error "You must give at least one requirement to install (see "pip help install")" However when running `pip install requests [security]` it installs or updates just fine. Also, I have all my packages upgraded but I'm still running into this login error.
