### ISSUE TITLE
unable to login..

### ISSUE THREAD

**Issue by dudeslife** [r0oth3x49/udemy-dl#106]
[-] Unable to extract login-form form
Traceback (most recent call last):
  File "udemy-dl.py", line 936, in <module>
    main()
  File "udemy-dl.py", line 841, in main
    udemy.ExtractAndDownload()

etc...

**Comment by RK4** [comment]
Same problem here. Unable to log-in.

**Comment by r0oth3x49** [comment]
@dudeslife ,@RK4  check #98 #100
