### ISSUE TITLE
Error on download courses 

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/udemy-dl#108]
anyone getting this same error?

> [*] : Downloading webpage..
> [*] : Extracting course information..
> [*] : Downloading 'course-course'.
> Traceback (most recent call last):
>   File "F:\udemy\_extractor.py", line 67, in _get_csrf_token
>     return match.group(1)
> AttributeError: 'NoneType' object has no attribute 'group'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "udemy-dl.py", line 646, in <module>
>     main()
>   File "udemy-dl.py", line 604, in main
>     udemy.ExtractAndDownload()
>   File "udemy-dl.py", line 280, in ExtractAndDownload
>     self.login()
>   File "udemy-dl.py", line 39, in login
>     extract_info.login(self.username, self.password)
>   File "F:\Udemy\udemy\udemy\_extractor.py", line 99, in login
>     csrf_token = self._get_csrf_token()
>   File "F:\Udemy\udemy\udemy\_extractor.py", line 70, in _get_csrf_token
>     return match.group(1)
> AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tofanelli** [comment]
And yes, i'm using the latest version =)

**Comment by sv000008** [comment]
Getting the following error:

[code]
[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'complete exchange 2013 practical guide'.
[*] : Trying to login as (*****@*****.***)...
[-] Unable to extract login-form form
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\Scripts\udemy-dl.py", line 924, in <module>
    main()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\Scripts\udemy-dl.py", line 829, in main
    udemy.ExtractAndDownload()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\Scripts\udemy-dl.py", line 291, in ExtractAndDownload
    self.login()
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\Scripts\udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\Scripts\udemy\_extractor.py", line 146, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\Scripts\udemy\_extractor.py", line 97, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\Scripts\udemy\_extractor.py", line 87, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\Scripts\udemy\_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'', '', html)
  File "C:\Users\*****\AppData\Local\Programs\Python\Python36\lib\re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
[/code]

**Comment by jonathans96** [comment]
I have this error - windows 10 

[-] Unable to extract login-form form
Traceback (most recent call last):
  File "udemy-dl.py", line 936, in <module>
    main()
  File "udemy-dl.py", line 891, in main
    udemy.ExtractAndDownload(quality=res)
  File "udemy-dl.py", line 303, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "D:\udemy-dl-master\udemy\_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "D:\udemy-dl-master\udemy\_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "D:\udemy-dl-master\udemy\_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "D:\udemy-dl-master\udemy\_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'', '', html)
  File "C:\Python27\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by r0oth3x49** [comment]
@tofanelli , @sv000008 , @jonathans96 check #98 , #100
