### ISSUE TITLE
Udemy Login Error

### ISSUE THREAD

**Issue by mynameismaxz** [r0oth3x49/udemy-dl#110]
I have some error with login to udemy.

```
Traceback (most recent call last):
  File "udemy-dl.py", line 936, in <module>
    main()
  File "udemy-dl.py", line 725, in main
    udemy.ExtractAndDownload()
  File "udemy-dl.py", line 303, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "/home/mynameismaxz/udemy-dl/udemy/_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "/home/mynameismaxz/udemy-dl/udemy/_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "/home/mynameismaxz/udemy-dl/udemy/_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "/home/mynameismaxz/udemy-dl/udemy/_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'<!--(?:(?!<!--).)*-->', '', html)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
```

**Comment by perezLamed** [comment]
I also got this error.

**Comment by EricLenSher** [comment]
me also
+1

**Comment by mskmx** [comment]
check #98, #100

**Comment by seanwhe** [comment]
To add information. I am experiencing this problem with udemy-dl==0.2.2-alpha.2

**Comment by seanwhe** [comment]
I can confirm that on Ubuntu Linux 16.04 installation of pyOpenSSL works.

# pip install pyOpenSSL
