### ISSUE TITLE
It does not allow to download purchased course if you disconnect while downloading

### ISSUE THREAD

**Issue by masifpak80** [r0oth3x49/udemy-dl#125]
I was downloading udemy course. Due to some reason i have to disconnect downloading. Now I am trying to download again but facing some problem.

> [-] Unable to extract login-form form
Traceback (most recent call last):
  File "udemy-dl.py", line 936, in <module>
    main()
  File "udemy-dl.py", line 725, in main
    udemy.ExtractAndDownload()
  File "udemy-dl.py", line 303, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "/opt/udemy-dl/udemy/_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "/opt/udemy-dl/udemy/_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "/opt/udemy-dl/udemy/_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "/opt/udemy-dl/udemy/_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'', '', html)
  File "/usr/lib/python3.4/re.py", line 179, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by tofanelli** [comment]
I'm getting this same error, but my internet connection wasn't disconnected.... it is working ok

**Comment by r0oth3x49** [comment]
@masifpak80 i 'm closing this with duplicate & will discuss about this error in #126 as both are same.
