### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by IsraelGboluwaga** [r0oth3x49/udemy-dl#130]
```
[-] Unable to extract login-form form
Traceback (most recent call last):
  File "udemy-dl.py", line 924, in <module>
    main()
  File "udemy-dl.py", line 829, in main
    udemy.ExtractAndDownload()
  File "udemy-dl.py", line 291, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "/Users/israel.arunah/Documents/udemy-dl/udemy-dl/udemy/_extractor.py", line 147, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "/Users/israel.arunah/Documents/udemy-dl/udemy-dl/udemy/_extractor.py", line 98, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "/Users/israel.arunah/Documents/udemy-dl/udemy-dl/udemy/_extractor.py", line 88, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "/Users/israel.arunah/Documents/udemy-dl/udemy-dl/udemy/_utils.py", line 80, in _hidden_inputs
    html = re.sub(r'<!--(?:(?!<!--).)*-->', '', html)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

```

**Comment by hiratsukaraphael** [comment]
Hello Israel, how did you resolve this issue? Thank you!

**Comment by IsraelGboluwaga** [comment]
I didn't. It works now though. Just pull the master branch now. It'll work. It was a break from the latest push.

**Comment by hiratsukaraphael** [comment]
Perfect, tks @IsraelGboluwaga
