### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not  'NoneType'

### ISSUE THREAD

**Issue by StevenNani** [r0oth3x49/udemy-dl#142]
This error is occurring only for few courses like I can download this course with no problem
https://www.udemy.com/unreale4
but not the below ones
https://www.udemy.com/intro-to-architectural-visualization-using-3ds-max-and-v-ray_zillus/learn/v4/
https://www.udemy.com/sketching-for-animators-who-cant-draw/learn/v4/
This is the error I get.
I thought it had something to do with the course title being long or something but, the below title works
https://www.udemy.com/speed-lunch-crunches-for-beginners-to-pixelogics-zbrush/learn/v4/

So, I don't think it has to do with the title.

> Traceback (most recent call last):
  File "udemy-dl.py", line 1187, in <module>
    main()
  File "udemy-dl.py", line 1028, in main
    udemy.course_download(path=options.output, quality=options.quality)
  File "udemy-dl.py", line 379, in course_download
    course = udemy.course(self.url, self.username, self.password)
  File "C:\Users\StevenNani\Desktop\udemy-dl-0.4\udemy\_udemy.py", line 37, in c
ourse
    return Udemy(url, username, password, basic, callback)
  File "C:\Users\StevenNani\Desktop\udemy-dl-0.4\udemy\_internal.py", line 44, i
n __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "C:\Users\StevenNani\Desktop\udemy-dl-0.4\udemy\_shared.py", line 61, in
__init__
    self._fetch_course()
  File "C:\Users\StevenNani\Desktop\udemy-dl-0.4\udemy\_internal.py", line 61, i
n _fetch_course
    self._chapters          =       [InternUdemyChapter(z) for z in self._info['
chapters']]
  File "C:\Users\StevenNani\Desktop\udemy-dl-0.4\udemy\_internal.py", line 61, i
n <listcomp>
    self._chapters          =       [InternUdemyChapter(z) for z in self._info['
chapters']]
  File "C:\Users\StevenNani\Desktop\udemy-dl-0.4\udemy\_internal.py", line 79, i
n __init__
    self._lectures          = [InternUdemyLecture(z) for z in chapter['lectures'
]]
  File "C:\Users\StevenNani\Desktop\udemy-dl-0.4\udemy\_internal.py", line 79, i
n <listcomp>
    self._lectures          = [InternUdemyLecture(z) for z in chapter['lectures'
]]
  File "C:\Users\StevenNani\Desktop\udemy-dl-0.4\udemy\_internal.py", line 97, i
n __init__
    self._duration          = int(self._info.get('duration')) or None
TypeError: int() argument must be a string, a bytes-like object or a number, not
 'NoneType'

**Comment by r0oth3x49** [comment]
@StevenNani you should upgrade to recent one this is already patched. check #133
