### ISSUE TITLE
Trying to download a course and getting the below error

### ISSUE THREAD

**Issue by Jaykaydre** [r0oth3x49/udemy-dl#143]
Traceback (most recent call last):
  File "udemy-dl.py", line 1187, in <module>
    main()
  File "udemy-dl.py", line 1028, in main
    udemy.course_download(path=options.output, quality=options.quality)
  File "udemy-dl.py", line 379, in course_download
    course = udemy.course(self.url, self.username, self.password)
  File "/home/kayode/Documents/udemy-dl/udemy/_udemy.py", line 37, in course
    return Udemy(url, username, password, basic, callback)
  File "/home/kayode/Documents/udemy-dl/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/home/kayode/Documents/udemy-dl/udemy/_shared.py", line 61, in __init__
    self._fetch_course()
  File "/home/kayode/Documents/udemy-dl/udemy/_internal.py", line 59, in _fetch_course
    self._chapters_count    =       self._info['total_chapters']
KeyError: 'total_chapters'

**Comment by r0oth3x49** [comment]
@Jaykaydre will check.

**Comment by harishpal2090** [comment]
have encounter with same error- please help.
[*] : Downloaded course information .. (done)
Traceback (most recent call last):
  File "udemy-dl.py", line 1187, in <module>
    main()
  File "udemy-dl.py", line 1039, in main
    udemy.course_list_down(chapter_number=options.chapter, lecture_number=options.lecture)
  File "udemy-dl.py", line 111, in course_list_down
    course = udemy.course(self.url, self.username, self.password)
  File "E:\Hacking\udemy-dl-master\udemy-dl-master\udemy\_udemy.py", line 37, in course
    return Udemy(url, username, password, basic, callback)
  File "E:\Hacking\udemy-dl-master\udemy-dl-master\udemy\_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "E:\Hacking\udemy-dl-master\udemy-dl-master\udemy\_shared.py", line 61, in __init__
    self._fetch_course()
  File "E:\Hacking\udemy-dl-master\udemy-dl-master\udemy\_internal.py", line 59, in _fetch_course
    self._chapters_count    =       self._info['total_chapters']
KeyError: 'total_chapters'

**Comment by r0oth3x49** [comment]
@Jaykaydre can you please provide course URL?

**Comment by Jaykaydre** [comment]
here you go : https://naspers.udemy.com/understand-javascript/learn/v4/overview

**Comment by tofanelli** [comment]
nice try to scam @Jaykaydre .... good try but needs a little bit more effort.... 

@r0oth3x49 ... just got this same error...  =\

**Comment by r0oth3x49** [comment]
@Jaykaydre i cannot reproduce the error with that course for me it is working fine.
![capture](https://user-images.githubusercontent.com/11024397/37256093-ee97aa7a-2577-11e8-893b-d5d342e0a562.png)

**Comment by r0oth3x49** [comment]
@tofanelli how can i reproduce i need the course URL to test against if i cannot reproduce i will not be able to fix.

**Comment by tofanelli** [comment]
Sure... i tried with this one

https://www.udemy.com/ajax-fetch-xhr/

but I think its because you are on version 0.4 and I on version 0.3....  most likely =\...  I will update and ping back here shortly

**Comment by tofanelli** [comment]
Yup... as i suspected, you released a new version and we didn't updated.... case closed =)


Mind I suggest something? Move the quizzes to a new folder and project files to another one, just like Udemy-dl from Nishad used to.... it was a nice way to keep the area clean and only see the videos / pdf to that folder.... i liked that way =)
