### ISSUE TITLE
float division by zero error while downloading subtitles

### ISSUE THREAD

**Issue by aviralwal** [r0oth3x49/udemy-dl#149]
While downloading a course, I got the following issue. The course was `https://www.udemy.com/complete-guitar-system-beginner-to-advanced/learn/v4/overview`

```
[*] : Downloading subtitle(s)
[*] : Downloading (048 Dexterity Exercise 2 - Ninja Fretting Hand Skills-en)
Traceback (most recent call last):
  File "udemy-dl.py", line 1187, in <module>
    main()
  File "udemy-dl.py", line 1183, in main
    udemy.course_download(path=options.output, quality=options.quality)
  File "udemy-dl.py", line 447, in course_download
    self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, lecture_subtitles=lecture_subtitles, lecture_assets=lecture_assets, filepath=filepath)
  File "udemy-dl.py", line 373, in download_lectures_and_captions
    self.download_subtitles(lecture_subtitles=lecture_subtitles, filepath=filepath)
  File "udemy-dl.py", line 322, in download_subtitles
    retval = subtitles.download(filepath=filepath, quiet=True, callback=self.show_progress)
  File "/Users/aviral/softwares/udemy-dl/udemy/_shared.py", line 750, in download
    eta  = (total - bytesdone) / (rate * 1024)
ZeroDivisionError: float division by zero
```

**Comment by r0oth3x49** [comment]
@aviralwal will fix ASAP thanks for the report.

**Comment by Drovosek01** [comment]
I have same problem.
![image](https://user-images.githubusercontent.com/29478700/37493189-28504566-28b5-11e8-9cad-808369de60ea.png)

**Comment by r0oth3x49** [comment]
@Drovosek01 both are different but i will take a look at this one as well. it will be good if you can paste the course link here.

**Comment by Drovosek01** [comment]
https://www.udemy.com/aws-solutions-architect-associate-practice-exams-sampler/learn/v4/

**Comment by r0oth3x49** [comment]
@Drovosek01 i have checked the udemy returns these questions in quiz class that's why you cannot download that because quizzes are out of scope.
