### ISSUE TITLE
What if the domain is different as  in my case. i.e instead of www the url is wipro . 

### ISSUE THREAD

**Issue by KarthickCSK** [r0oth3x49/udemy-dl#15]
I tried to change the source code but got an error 👎 

[INFO-107] Trying to log in ...
Traceback (most recent call last):
  File "C:\python\lib\site-packages\udemy_dl\udemy_dl.py", line 97, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "udemy-dl", line 7, in <module>
    main()
  File "C:\python\lib\site-packages\udemy_dl\udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "C:\python\lib\site-packages\udemy_dl\udemy_dl.py", line 658, in udemy_dl
    login(username, password)
  File "C:\python\lib\site-packages\udemy_dl\udemy_dl.py", line 109, in login
    csrf_token = get_csrf_token()
  File "C:\python\lib\site-packages\udemy_dl\udemy_dl.py", line 102, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by r0oth3x49** [comment]
@KarthickCSK currently this repo does not support any sub domain of udemy. may be in next release i 'll add the functionality for that you can contact me on my social account [Nasir Khan (r0oth3x49)](https://www.facebook.com/r0oth3x49).

**Comment by r0oth3x49** [comment]
@KarthickCSK the latest release has the patch for udemy business account i have tested against on of my friends account..

**Comment by nagaminash** [comment]
![screen shot 2018-06-06 at 10 05 37 pm](https://user-images.githubusercontent.com/40000642/41052292-04c0325c-69d6-11e8-8206-555811750b7e.png)
Issue still persists for subdomains of udemy. wipro.udemy.com, Tried to modify the source Code no luck, Could you please look into it
