### ISSUE TITLE
[ERROR-61] Exception

### ISSUE THREAD

**Issue by seanwhe** [r0oth3x49/udemy-dl#165]
Today I tried downloading some courses and received the following on 
Ubuntu 16.04 LTS with udemy-dl==0.2.2-alpha.2 and python-pptx, pyOpenSSL aria2 and ffmpeg installed.

[INFO-133] Trying to log in ...
[ERROR-61] Exception
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 947, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 744, in udemy_dl
    login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 134, in login
    csrf_token = get_csrf_token()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 128, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by seanwhe** [comment]
Login seems to be a problem again

**Comment by r0oth3x49** [comment]
@seanwhe i think you are not using this Repo but the One on python's repository. check this issue #152

**Comment by seanwhe** [comment]
Yes I am installing with from pip

**Comment by r0oth3x49** [comment]
@seanwhe clone this repository and try to download if you face any error with this repo then let me know. i did not added this to python's repository yet. so this utility cannot be installed with `pip` but can only be clone from github.
