### ISSUE TITLE
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by PublicPlace** [r0oth3x49/udemy-dl#167]
Error message while trying to dl:
https://www.udemy.com/hands-on-sketch-4-masterclass-learn-web-and-mobile-design/

  File "udemy-dl.py", line 1201, in <module>
    main()
  File "udemy-dl.py", line 898, in main
    udemy.course_list_down(chapter_number=options.chapter, lecture_number=options.lecture)
  File "udemy-dl.py", line 125, in course_list_down
    course = udemy.course(self.url, self.username, self.password)
  File "/Users/###/Downloads/udemy-dl/udemy/_udemy.py", line 37, in course
    return Udemy(url, username, password, basic, callback)
  File "/Users/###/Downloads/udemy-dl/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/Users/###/Downloads/udemy-dl/udemy/_shared.py", line 61, in __init__
    self._fetch_course()
  File "/Users/###/Downloads/udemy-dl/udemy/_internal.py", line 54, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "/Users/###/Downloads/udemy-dl/udemy/_extract.py", line 448, in _real_extract
    _udemy['total_lectures'] = self._lectures_count(_udemy['chapters'])
  File "/Users/###/Downloads/udemy-dl/udemy/_extract.py", line 293, in _lectures_count
    lectures += lectures_count
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

**Comment by tofanelli** [comment]
have you tried to download any other course? Because im downloading a course right now and its ok... working flawlessly =)

**Comment by PublicPlace** [comment]
all the others indeed work flawlessly… maybe some escape character issues …

**Comment by r0oth3x49** [comment]
@PublicPlace i don't have this course in my account so i cannot test against this one. but testing on other courses udemy-dl works fine for me. if you want me to test and fix error on this course, I might need your account.

**Comment by hechanghong** [comment]
I got same issue today for one course using below cli, but working well for other courses as of now.

>python udemy-dl.py -u xxxxxxxxxxxxxx -p xxxxxxxxxxxxx https://www.udemy.com/actions-on-google-app-google-assistant/learn/v4/overview -o /Users/michaelhe/mydoc/udemy-lectures

-------------------Log------------------------
[+] : Logged in successfully.
[*] : Downloading course information .. \Traceback (most recent call last):
  File "udemy-dl.py", line 1187, in <module>
    main()
  File "udemy-dl.py", line 1183, in main
    udemy.course_download(path=options.output, quality=options.quality)
  File "udemy-dl.py", line 379, in course_download
    course = udemy.course(self.url, self.username, self.password)
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_udemy.py", line 37, in course
    return Udemy(url, username, password, basic, callback)
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_shared.py", line 61, in __init__
    self._fetch_course()
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_internal.py", line 54, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_extract.py", line 433, in _real_extract
    _udemy['total_lectures'] = self._lectures_count(_udemy['chapters'])
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_extract.py", line 293, in _lectures_count
    lectures += lectures_count
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

**Comment by hechanghong** [comment]
@tofanelli 
thanks for your advice, but it is not working for me.
I got the same error like below. By the way, I am using Mac, not windows.


[+] : Logged in successfully.
[*] : Downloading course information .. \Traceback (most recent call last):
  File "udemy-dl.py", line 1187, in <module>
    main()
  File "udemy-dl.py", line 1183, in main
    udemy.course_download(path=options.output, quality=options.quality)
  File "udemy-dl.py", line 379, in course_download
    course = udemy.course(self.url, self.username, self.password)
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_udemy.py", line 37, in course
    return Udemy(url, username, password, basic, callback)
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_shared.py", line 61, in __init__
    self._fetch_course()
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_internal.py", line 54, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_extract.py", line 433, in _real_extract
    _udemy['total_lectures'] = self._lectures_count(_udemy['chapters'])
  File "/Users/michaelhe/myMacBook/udemy-dl/udemy/_extract.py", line 293, in _lectures_count
    lectures += lectures_count
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
