### ISSUE TITLE
Some weird error

### ISSUE THREAD

**Issue by takasurazeem** [r0oth3x49/udemy-dl#217]
`Traceback (most recent call last):
  File "udemy-dl.py", line 1441, in <module>
    main()
  File "udemy-dl.py", line 1437, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 436, in course_download
    course = udemy.course(url=self.url, username=self.username, password=self.password, cookies=self.cookies)
  File "/Users/takasur/Desktop/udemy-dl/udemy/_udemy.py", line 38, in course
    return Udemy(url, username, password, cookies, basic, callback)
  File "/Users/takasur/Desktop/udemy-dl/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/Users/takasur/Desktop/udemy-dl/udemy/_shared.py", line 62, in __init__
    self._fetch_course()
  File "/Users/takasur/Desktop/udemy-dl/udemy/_internal.py", line 63, in _fetch_course
    self._chapters          =       [InternUdemyChapter(z) for z in self._info['chapters']]
  File "/Users/takasur/Desktop/udemy-dl/udemy/_internal.py", line 83, in __init__
    self._lectures_count    = chapter['lectures_count']
KeyError: 'lectures_count'`

This is all I see in the console and I have latest version of the udemy-dl downloaded.

**Comment by r0oth3x49** [comment]
@takasurazeem follow issue reporting guideline else i will close the issue
