### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by Vanellopee** [r0oth3x49/udemy-dl#239]
udemy-dl version 0.5
python version 2.7.15
OS Ubuntu 16.04LTS

Some course is fine which can be download entirely, but some course have problem, like https://www.udemy.com/spring-hibernate-tutorial/  this course have 544 lectures, does it is too much to handle the content? 
The Error below will encounter when I download Spring & Hibernate for Beginne course

Traceback (most recent call last):on ..
  File "udemy-dl.py", line 1441, in <module>
    main()
  File "udemy-dl.py", line 1437, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 436, in course_download
    course = udemy.course(url=self.url, username=self.username, password=self.password, cookies=self.cookies)
  File "C:\Users\Ju\Downloads\udemy-dl-master\udemy-dl-master\udemy\_udemy.py", line 38, in course
    return Udemy(url, username, password, cookies, basic, callback)
  File "C:\Users\Ju\Downloads\udemy-dl-master\udemy-dl-master\udemy\_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "C:\Users\Ju\Downloads\udemy-dl-master\udemy-dl-master\udemy\_shared.py", line 62, in __init__
    self._fetch_course()
  File "C:\Users\Ju\Downloads\udemy-dl-master\udemy-dl-master\udemy\_internal.py", line 56, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "C:\Users\Ju\Downloads\udemy-dl-master\udemy-dl-master\udemy\_extract.py", line 350, in _real_extract
    course_json = self._extract_course_json(course_id)
  File "C:\Users\Ju\Downloads\udemy-dl-master\udemy-dl-master\udemy\_extract.py", line 149, in _extract_course_json
    resp = self._session._get(url).json()
  File "C:\Python27\lib\site-packages\requests\models.py", line 884, in json
    self.content.decode(encoding), **kwargs
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by r0oth3x49** [comment]
@Vanellopee i will check & try to fix ASAP.

**Comment by shaneog** [comment]
Any luck with this? I am having the same error with the same course!

**Comment by Rajssss** [comment]
I am still having the same problem with a huge course of 80+ hours https://www.udemy.com/course/complete-networking-fundamentals-course-ccna-start/

**Comment by kumarnipun** [comment]
I suggest. Better go for cbt nugget
