### ISSUE TITLE
Script don't download with and after lectures with /

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/udemy-dl#250]
Hey @r0oth3x49 

I just noticed something.... There are a few courses, where has a / on lectures name, the script can't download the lecture with the /  neither any lecture after it, even if I use the flag '--lecture-start' to get the lecture after it..

It returns this error 
> Traceback (most recent call last):
  File "udemy-dl.py", line 1441, in <module> main()
  File "udemy-dl.py", line 1437, in main udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 510, in course_download lecture.dump(filepath=filepath, unsafe=unsafe)
  File "F:\Udemy\udemy-dl\udemy\_shared.py", line 253, in dump with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 

Cheers =)

**Comment by r0oth3x49** [comment]
@tofanelli please do follow Issue Reporting guideline i cannot fix the issue until unless i don't understand what the root cause is and what is the url etc...

**Comment by tofanelli** [comment]
@r0oth3x49 do you have an email address where I can send you more data?

**Comment by r0oth3x49** [comment]
@tofanelli yeah. [you can email me](mailto:nasir251292@gmail.com)
