### ISSUE TITLE
SRT NoneType error 

### ISSUE THREAD

**Issue by FloLaco** [r0oth3x49/udemy-dl#260]
Hello,

I try to download this course : https://www.udemy.com/python-programming-for-real-life-networking-use/
But after one lesson, I got this error. And If I relunch it, I got the same error.

```
[*] : Downloading subtitle(s)
[*] : Downloading (127 Application 5 - Part 5-en)
[*] : Subtitle : '127 Application 5 - Part 5-en' (already downloaded).
Traceback (most recent call last):
  File "udemy-dl.py", line 1441, in <module>
    main()
  File "udemy-dl.py", line 1437, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 511, in course_download
    self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, lecture_subtitles=lecture_subtitles, lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
  File "udemy-dl.py", line 427, in download_lectures_and_captions
    self.download_subtitles(lecture_subtitles=lecture_subtitles, filepath=filepath, unsafe=unsafe)
  File "udemy-dl.py", line 378, in download_subtitles
    self.convert(filename=filename)
  File "/home/rian/Documents/udemy/udemy-dl/udemy/_vtt2srt.py", line 142, in convert
    _start, _end  = m.group(1), m.group(2)
AttributeError: 'NoneType' object has no attribute 'group'
rian@lubuntu:~/Documents/udemy/udemy-dl$ 

```

**Comment by FloLaco** [comment]
I've found the error : 

In the .vtt file stored by the script, I saw this : 
```
00:00:10.350 --> 00:00:17.650
And as a best practice, inside this loop, you should also read the code in a try except block to cover the00:00:17.710 --> 00:00:19.580key
board interrupt exception.
```

There's an error in the file, and because of the `-->`, the script crash.
I've edited the script to avoid this : 
https://github.com/r0oth3x49/udemy-dl/blob/4e0c95a6bbe145f8ac8355c2b19d3fce3dcfcaed/udemy/_vtt2srt.py#L140
```
                            for line in content[index:]:
                                m = re.match(r'^((?:\d{1,2}:){1,2}\d{2}\.\d{3})\s-->\s((?:\d{1,2}:){1,2}\d{2}\.\d{3})', line)
                                if m:
                                    _start, _end  = m.group(1), m.group(2)
```

**Comment by christian-weiss** [comment]
Confirmed. 
I got the same error, but on a different course: 
https://www.udemy.com/learn-devops-advanced-kubernetes-usage/
after second lecture in chapter three.

Confirmed. This fix works.
I will create a pull request to merge it.

**Comment by r0oth3x49** [comment]
@FloLaco will fix ASAP.

**Comment by FloLaco** [comment]
@r0oth3x49 I've just fetched the updated master branche and now it works !
