### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by ipkpjersi** [r0oth3x49/udemy-dl#269]
![](https://i.imgur.com/c0RcUHn.png)
Here is my line I use to download:
python3.5 udemy-dl.py -u email -p password https://www.udemy.com/spring-hibernate-tutorial/learn/v4/overview/ -q 720 --skip-sub

**Comment by ronkiwest** [comment]
I have similar issue , when collecting course information it prints a Traceback error.Here is the full text:

Traceback (most recent call last):
  File "C:\Users\Lenovo\udemy-dl\udemy-dl.py", line 1201, in <module>
    main()
  File "C:\Users\Lenovo\udemy-dl\udemy-dl.py", line 1193, in main
    udemy.course_download(skip_captions=options.skip_captions, path=options.output, quality=options.quality)
  File "C:\Users\Lenovo\udemy-dl\udemy-dl.py", line 393, in course_download
    course = udemy.course(self.url, self.username, self.password)
  File "C:\Users\Lenovo\udemy-dl\udemy\_udemy.py", line 37, in course
    return Udemy(url, username, password, basic, callback)
  File "C:\Users\Lenovo\udemy-dl\udemy\_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "C:\Users\Lenovo\udemy-dl\udemy\_shared.py", line 61, in __init__
    self._fetch_course()
  File "C:\Users\Lenovo\udemy-dl\udemy\_internal.py", line 61, in _fetch_course
    self._chapters          =       [InternUdemyChapter(z) for z in self._info['chapters']]
  File "C:\Users\Lenovo\udemy-dl\udemy\_internal.py", line 61, in <listcomp>
    self._chapters          =       [InternUdemyChapter(z) for z in self._info['chapters']]
  File "C:\Users\Lenovo\udemy-dl\udemy\_internal.py", line 79, in __init__
    self._lectures_count    = chapter['lectures_count']
KeyError: 'lectures_count'
