### ISSUE TITLE
unable to download any courses - python: can't open file 'udemy-dl.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by garrincha33** [r0oth3x49/udemy-dl#271]
I have cloned the most recent repo successfully but im getting the attached error when trying to download a course. Can anyone provide a fix for this please?   thanks
![screen shot 2018-08-25 at 14 40 23](https://user-images.githubusercontent.com/1871219/44618791-da7b8180-a874-11e8-844b-24c75fd153be.png)

**Comment by r0oth3x49** [comment]
@garrincha33 did you even cd (change directory) to the root level where `udemy-dl.py` is available. cd to udemy-dl directory and then try to run it will work.

**Comment by garrincha33** [comment]
meh what a dumbass :-)   thanks all sorted

**Comment by Ajob41** [comment]
please help I am getting this error Traceback (most recent call last):
  File "udemy-dl.py", line 7, in <module>
    import udemy
  File "/mnt/c/Users/4488/desktop/python/udemy-dl/udemy/__init__.py", line 32, in <module>
    from ._udemy import course
  File "/mnt/c/Users/4488/desktop/python/udemy-dl/udemy/_udemy.py", line 26, in <module>
    from ._internal import InternUdemyCourse as Udemy
  File "/mnt/c/Users/4488/desktop/python/udemy-dl/udemy/_internal.py", line 30, in <module>
    from ._extract import Udemy
  File "/mnt/c/Users/4488/desktop/python/udemy-dl/udemy/_extract.py", line 50, in <module>
    from ._sanitize import (
  File "/mnt/c/Users/4488/desktop/python/udemy-dl/udemy/_sanitize.py", line 10, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'
