### ISSUE TITLE
Linux error: TypeError: coercing to Unicode: need string or buffer, bool found

### ISSUE THREAD

**Issue by jmishal** [r0oth3x49/udemy-dl#274]
Good day,

Receiving the following error on Debian Linux 7 64bit , python 2.7.6, python 3
This error comes I almost finished, after downloading most of the courses. 

`[*] : Subtitle : '107 A Deeper Dive into Aperture-en' (already downloaded).
Traceback (most recent call last):
  File "udemy-dl.py", line 1441, in <module>
    main()
  File "udemy-dl.py", line 1280, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 511, in course_download
    self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, lecture_subtitles=lecture_subtitles, lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
  File "udemy-dl.py", line 427, in download_lectures_and_captions
    self.download_subtitles(lecture_subtitles=lecture_subtitles, filepath=filepath, unsafe=unsafe)
  File "udemy-dl.py", line 378, in download_subtitles
    self.convert(filename=filename)
  File "/root/udemy/udemy-dl-master/udemy/_vtt2srt.py", line 96, in convert
    self._write_srtcontent(fname, timecode)
  File "/root/udemy/udemy-dl-master/udemy/_vtt2srt.py", line 52, in _write_srtcontent
    fd.write(content)
  File "/usr/lib/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
TypeError: coercing to Unicode: need string or buffer, bool found
`

**Comment by ArjonBu** [comment]
I am having the same problem myself. 

Course url: udemy.com/photography-masterclass-complete-guide-to-photography
Command used to download: 

```
/udemy-dl.py https://mybusiness.udemy.com/photography-masterclass-complete-guide-to-photography/ -o "/home/user/udemy/videos/" -u email -p password
```
