### ISSUE TITLE
AttributeError: module 'idna' has no attribute 'encode'

### ISSUE THREAD

**Issue by kfung21** [r0oth3x49/udemy-dl#279]
**Summary**:
I am using Windows 7 and python 3.6.6.  When I try to download the course <a href="https://www.udemy.com/the-web-developer-bootcamp/">Web Developer Bootcamp</a> I get an error saying <i>AttributeError: module 'idna' has no attribute 'encode'</i>.  I have installed the requirements using pip. Please help. Thank you. 

**Console Error:**
Traceback (most recent call last):
  File "udemy-dl.py", line 1441, in <module>
    main()
  File "udemy-dl.py", line 1280, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=
ptions.unsafe)
  File "udemy-dl.py", line 436, in course_download
    course = udemy.course(url=self.url, username=self.username, password=self.p
ssword, cookies=self.cookies)
  File "C:\Users\Kevin\Desktop\Udemy Courses\udemy-dl-master\udemy\_udemy.py",
ine 38, in course
    return Udemy(url, username, password, cookies, basic, callback)
  File "C:\Users\Kevin\Desktop\Udemy Courses\udemy-dl-master\udemy\_internal.py
, line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "C:\Users\Kevin\Desktop\Udemy Courses\udemy-dl-master\udemy\_shared.py",
line 62, in __init__
    self._fetch_course()
  File "C:\Users\Kevin\Desktop\Udemy Courses\udemy-dl-master\udemy\_internal.py
, line 50, in _fetch_course
    auth = self._login(username=self._username, password=self._password)
  File "C:\Users\Kevin\Desktop\Udemy Courses\udemy-dl-master\udemy\_extract.py"
 line 97, in _login
    self._session = auth.authenticate()
  File "C:\Users\Kevin\Desktop\Udemy Courses\udemy-dl-master\udemy\_auth.py", l
ne 71, in authenticate
    form = self._form_hidden_input('login-form')
  File "C:\Users\Kevin\Desktop\Udemy Courses\udemy-dl-master\udemy\_auth.py", l
ne 50, in _form_hidden_input
    webpage = self._session._get(LOGIN_POPUP).text
  File "C:\Users\Kevin\Desktop\Udemy Courses\udemy-dl-master\udemy\_session.py"
 line 47, in _get
    return self._session.get(url, headers=self._headers)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line
21, in get
    return self.request('GET', url, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line
08, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line
18, in send
    r = adapter.send(request, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line
40, in send
    timeout=timeout
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py",
ine 601, in urlopen
    chunked=chunked)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py",
ine 346, in _make_request
    self._validate_conn(conn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py",
ine 850, in _validate_conn
    conn.connect()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line
337, in connect
    cert = self.sock.getpeercert()
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py
, line 348, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py
, line 222, in get_subj_alt_name
    for name in ext.get_values_for_type(x509.DNSName)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py
, line 222, in <listcomp>
    for name in ext.get_values_for_type(x509.DNSName)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py
, line 175, in _dnsname_to_stdlib
    name = idna_encode(name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py
, line 172, in idna_encode
    return prefix.encode('ascii') + idna.encode(name)
AttributeError: module 'idna' has no attribute 'encode'

**Comment by Civmwa** [comment]
@kfung21  getting exact same error when trying to convert a python Twint to Exe via cx_freeze. Did you get any help?

![twint to exe using cx_freeze error](https://user-images.githubusercontent.com/38909818/45673252-e0424b00-bb32-11e8-81e9-7f8f2d571784.PNG)

**Comment by assoft** [comment]
Same error

<img width="1314" alt="ekran resmi 2018-09-18 12 08 25" src="https://user-images.githubusercontent.com/835239/45677102-10421c00-bb3c-11e8-902e-dc6e640500cb.png">

**Comment by kfung21** [comment]
> @kfung21 getting exact same error when trying to convert a python Twint to Exe via cx_freeze. I'm using python 3.6.5 windows 10 64 bit. Did you get any help?
> 
> ![twint to exe using cx_freeze error](https://user-images.githubusercontent.com/38909818/45673252-e0424b00-bb32-11e8-81e9-7f8f2d571784.PNG)

I actually went with another python app instead. It works very well:
[udemy-downloader-gui](https://github.com/FaisalUmair/udemy-downloader-gui)

**Comment by r0oth3x49** [comment]
@kfung21 so now this issue can be closed as this is not related to the repository.
