### ISSUE TITLE
no no no

### ISSUE THREAD

**Issue by gamernewone** [r0oth3x49/udemy-dl#297]
Traceback (most recent call last):
  File "/home/ridy/.local/bin/udemy-dl", line 7, in <module>
    main()
  File "/home/ridy/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/home/ridy/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 658, in udemy_dl
    login(username, password)
  File "/home/ridy/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 109, in login
    csrf_token = get_csrf_token()
  File "/home/ridy/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 99, in get_csrf_token
    session.get('http://www.udemy.com/user/logout')
  File "/home/ridy/.local/lib/python2.7/site-packages/udemy_dl/udemy_dl.py", line 66, in get
    return self.session.get(url, headers=self.headers)
  File "/home/ridy/.local/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/home/ridy/.local/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ridy/.local/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/ridy/.local/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

**Comment by r0oth3x49** [comment]
@gamernewone you are not using this utility, clone this one, (**Note :-** `this cannot be installed via pip`) so the error does not belongs to this repository.
