### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by Chlitzxer** [r0oth3x49/udemy-dl#31]
After trying to download a course I been getting the following:

[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'learn'.
Traceback (most recent call last):
  File "C:\U2\udemy-dl.py", line 894, in <module>
    main()
  File "C:\U2\udemy-dl.py", line 799, in main
    udemy.ExtractAndDownload()
  File "C:\U2\udemy-dl.py", line 281, in ExtractAndDownload
    self.login()
  File "C:\U2\udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "C:\U2\udemy\_extractor.py", line 101, in login
    csrf_token = self._get_csrf_token()
  File "C:\U2\udemy\_extractor.py", line 72, in _get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Thanks!

**Comment by r0oth3x49** [comment]
@Chlitzxer which course are you downloading i cannot reproduce this error.
