### ISSUE TITLE
Getting issue AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by harshal-nehete** [r0oth3x49/udemy-dl#310]
```
[INFO-107] Trying to log in ...
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 658, in udemy_dl
    login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 109, in login
    csrf_token = get_csrf_token()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 102, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

I am using Ubuntu 18.04 and latest version of udemy-dl

**Comment by UADACID** [comment]
I also experienced it, any solution ?
