### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 45: ordinal not in range(128)

### ISSUE THREAD

**Issue by oijm17** [r0oth3x49/udemy-dl#314]
OS: macOS Mojave
Udemy-dl v0.5
Command: sudo python udemy-dl.py -u EMAIL -p PASSWORD --unsafe https://www.udemy.com/curso-completo-de-hacking-etico/learn -q 1080 -o "/Volumes/WD/"

Getting Below error

Traceback (most recent call last):
  File "udemy-dl.py", line 1441, in <module>
    main()
  File "udemy-dl.py", line 1437, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 448, in course_download
    course_path    = "%s\\%s" % (path, course_name) if os.name == 'nt' else "%s/%s" % (path, course_name)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 45: ordinal not in range(128)

**Comment by r0oth3x49** [comment]
@oijm17 i might need your account to reproduce and fix, Because i don't have access to this course. so you can [email me](mailto:nasir251292@gmail.com) your credentials.
