### ISSUE TITLE
Trying to download an Arabic course and getting error

### ISSUE THREAD

**Issue by Murtadhajfadhil** [r0oth3x49/udemy-dl#321]
Trying to download this course
https://www.udemy.com/unity-course-in-arabic/
which is an Arabic course and getting an error 'file length is too long to create.' because the files name is in random numbers format.

[*] : Lecture(s) : (1 of 3)
[*] : Downloading (001 16031610160116101577 1575158715781582158315751605 157516041583160815851577 160815781581160516101604 157516041605160815751583 15751604157515901575160116101577 16081575160416071583157516101575)
[*] : Lecture : '001 16031610160116101577 1575158715781582158315751605 157516041583160815851577 160815781581160516101604 157516041605160815751583 15751604157515901575160116101577 16081575160416071583157516101575' (download skipped).
[-] : file length is too long to create. try downloading to other drive (e.g :- -o 'E:\')

[*] : Lecture(s) : (3 of 3)
[*] : Downloading (003 15711585157615751581 1575160415751604159315751576 160816071604 15781591160816101585 1575160415751604159315751576 1610158116021602 16051576157516041594 15911575157416041577 16071604 16071608 158716071604 15751604158515761581 16051606 1575160415751604159315751576)
[*] : Lecture : '003 15711585157615751581 1575160415751604159315751576 160816071604 15781591160816101585 1575160415751604159315751576 1610158116021602 16051576157516041594 15911575157416041577 16071604 16071608 158716071604 15751604158515761581 16051606 1575160415751604159315751576' (download skipped).
[-] : file length is too long to create. try downloading to other drive (e.g :- -o 'E:\')

[*] : Downloading chapter : (2 of 26)
[+] : Chapter (02 15781581159016101585 1576161015741577 15751604159316051604 160815781606158616101604 1575160415761585157516051580)
[*] : Found (2) lectures ...

[*] : Lecture(s) : (1 of 2)
[*] : Downloading (004 15781581160516101604 160815781606158616101604 1575160416101608160615781610 160815761585157516051580 15781581158516101585 15751604158916081585 16081575157516041601160815781608158816081576)
[*] : Lecture : '004 15781581160516101604 160815781606158616101604 1575160416101608160615781610 160815761585157516051580 15781581158516101585 15751604158916081585 16081575157516041601160815781608158816081576' (download skipped).
[-] : file length is too long to create. try downloading to other drive (e.g :- -o 'E:\')
Traceback (most recent call last):
  File "udemy-dl.py", line 1443, in <module>
    main()
  File "udemy-dl.py", line 1439, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 510, in course_download
    lecture.dump(filepath=filepath, unsafe=unsafe)
  File "F:\udemy-dl-master\udemy\_shared.py", line 253, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\udemy-dl-master\\unity-course-in-arabic\\02 15781581159016101585 1576161015741577 15751604159316051604 160815781606158616101604 1575160415761585157516051580\\005 1605160415751581159215751578 159316041609 15781606158616101604 1575160415761585157516051580 15751604160515911604160815761577.html'

**Comment by r0oth3x49** [comment]
@Murtadhajfadhil there is switch `--unsafe` which you can use. before creating an issue please explore the tool or at least take a look at readme file if there is any help which can solve your problem. If not only then create the issue.
