### ISSUE TITLE
Getting issue AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by StephenGenusa** [r0oth3x49/udemy-dl#326]
The last report of this was marked as irrelevant. At least three people have experienced this and would like to know how to resolve this please.

[INFO-107] Trying to log in ...
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 658, in udemy_dl
    login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 109, in login
    csrf_token = get_csrf_token()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 102, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by StephenGenusa** [comment]
[INFO-107] Trying to log in ...
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/udemy_dl/udemy_dl.py", line 97, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/lib/python3.7/site-packages/udemy_dl/udemy_dl.py", line 658, in udemy_dl
    login(username, password)
  File "/usr/lib/python3.7/site-packages/udemy_dl/udemy_dl.py", line 109, in login
    csrf_token = get_csrf_token()
  File "/usr/lib/python3.7/site-packages/udemy_dl/udemy_dl.py", line 102, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by r0oth3x49** [comment]
@StephenGenusa i have discussed so many times in issues like that and also written in `README.md` that this utility is not available at `Pypi` which means you cannot download / install this from pypi using `pip` command. the utility on pypi is owned by some one else, So either report to the original author for fix or clone this repository and use.

if you mouse over to the label `Irrelevant` it also stats the same, that this issue is not related to this repository. 

### udemy-dl (by me r0oth3x49) is not available on PYPI. Clone/Download it from here on github and use.

**Comment by StephenGenusa** [comment]
Thank you for the explanation. It was missing from the previous report.

**Comment by spphinslove** [comment]
try use firefox to get the cookies
