### ISSUE TITLE
Error to download course in Portuguese

### ISSUE THREAD

**Issue by tofanelli** [r0oth3x49/udemy-dl#337]
Hey @r0oth3x49 

I'm trying to download a course with the latest version, and I'm getting this issue here

> Traceback (most recent call last):
>   File "udemy-dl.py", line 1443, in <module>
>     main()
>   File "udemy-dl.py", line 1439, in main
>     udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
>   File "udemy-dl.py", line 511, in course_download
>     self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, lecture_subtitles=lecture_subtitles, lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
>   File "udemy-dl.py", line 429, in download_lectures_and_captions
>     self.download_assets(lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
>   File "udemy-dl.py", line 338, in download_assets
>     assets.download(filepath=filepath, unsafe=unsafe, quiet=True, callback=self.show_progress)
>   File "F:\Udemy\udemy-dl\udemy\_shared.py", line 594, in download
>     return self._write_external_links(filepath)
>   File "F:\Udemy\udemy-dl\udemy\_shared.py", line 521, in _write_external_links
>     with open('{}.txt'.format(filename), 'a') as f:
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 69-70: ordinal not in range(128)

The weird part is that the script downloaded one lecture, but the second one just stopped and returned this error.... any light?

**Comment by tofanelli** [comment]
And [here](https://www.udemy.com/courses/search/?src=ukw&q=javascript&p=1&lang=pt&price=price-free) you have some free portuguese courses to test...

**Comment by r0oth3x49** [comment]
@tofanelli i will try to reproduce and fix on weekend.

**Comment by tofanelli** [comment]
There is something odd here @r0oth3x49 ... I just downloaded a whole course in portuguese, but another one is not working ... it just crashes after download the first lecture...

**Comment by r0oth3x49** [comment]
@r0oth3x49 how can reproduce it will be great if you can provide me a specific course where i can directly reproduce and fix instead of checking the above courses one by one.

**Comment by linneudm** [comment]
sup guys! I got an error today, maybe it's the same case. Has this issue error been reproduced in Windows? I have not tried Linux yet.

**Comment by linneudm** [comment]
![image](https://user-images.githubusercontent.com/16892488/54126628-bdf50000-43e6-11e9-936e-e6ed917ca579.png)

**Comment by linneudm** [comment]
I found it as temporary workaround by changing **line 42** of the **_vtt2srt.py** file:

f = codecs.open (filename = fname, encoding = 'utf-8', **errors = 'ignore'**)

**Comment by tofanelli** [comment]
Just updated pip, and the message has changed a little bit

>>> Traceback (most recent call last):
  File "udemy-dl.py", line 1443, in <module>
    main()
  File "udemy-dl.py", line 1439, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 511, in course_download
    self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, lecture_subtitles=lecture_subtitles, lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
  File "udemy-dl.py", line 429, in download_lectures_and_captions
    self.download_assets(lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
  File "udemy-dl.py", line 338, in download_assets
    assets.download(filepath=filepath, unsafe=unsafe, quiet=True, callback=self.show_progress)
  File "F:\Udemy\udemy-dl\udemy\_shared.py", line 594, in download
    return self._write_external_links(filepath)
  File "F:\Udemy\udemy-dl\udemy\_shared.py", line 521, in _write_external_links
    with open('{}.txt'.format(filename), 'a') as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 50: ordinal not in range(128)

and using what @linneudm  said, didn't worked =\

**Comment by r0oth3x49** [comment]
@tofanelli again as i said please it will be great if you can provide me a course url where i can reproduce the error & fix, i will do this on the weekend.



> 
> 
> I found it as temporary workaround by changing **line 42** of the **_vtt2srt.py** file:
> 
> f = codecs.open (filename = fname, encoding = 'utf-8', **errors = 'ignore'**)

the error @tofanelli is facing is different then what you are doing a workaround for this work around might work for subtitles.

**Comment by tofanelli** [comment]
@r0oth3x49 please take a look in your email inbox =)
