### ISSUE TITLE
Invalid URL 'view_html': No schema supplied. Perhaps you meant http://view_html?

### ISSUE THREAD

**Issue by wkremser** [r0oth3x49/udemy-dl#34]
When i try to list infos from a specific course i get the following error

Traceback (most recent call last):
  File "./udemy-dl.py", line 892, in <module>
    main()
  File "./udemy-dl.py", line 657, in main
    udemy.ListDown()
  File "./udemy-dl.py", line 258, in ListDown
    sz,in_MB    = self.get_filsize(url)
  File "./udemy-dl.py", line 182, in get_filsize
    req             = get(url, stream=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'view_html': No schema supplied. Perhaps you meant http://view_html?

i have this configuration file:
{
	"username" 		: "[my account]",
	"password" 		: "[my password]",
	"resolution" 		: "1080",
	"output" 		: ""
}

script execution:
python3 ./udemy-dl.py  -l https://www.udemy.com/mastering-ansible/learn/v4/

**Comment by r0oth3x49** [comment]
@wkremser good catch will fix it ASAP 👍
