### ISSUE TITLE
Unable to download the udemy course

### ISSUE THREAD

**Issue by ameyaagashe** [r0oth3x49/udemy-dl#364]
Hi,

I am trying to download the course on my windows 10 Home Edition OS. The too, I used is, is git bash for Windows, I used the instructions as below

`$ python udemy-dl.py -u xxxxxx@gmail.com -p xxxxxx https://www.udemy.com/70533-azure`

However, I get an error message as below:

```
Traceback (most recent call last):
  File "udemy-dl.py", line 7, in <module>
    import udemy
  File "C:\OnlyOnMyPC\udemy-dl\udemy\__init__.py", line 32, in <module>
    from ._udemy import course
  File "C:\OnlyOnMyPC\udemy-dl\udemy\_udemy.py", line 26, in <module>
    from ._internal import InternUdemyCourse as Udemy
  File "C:\OnlyOnMyPC\udemy-dl\udemy\_internal.py", line 29, in <module>
    from ._colorized import *
  File "C:\OnlyOnMyPC\udemy-dl\udemy\_colorized\__init__.py", line 25, in <module>
    from .colors import *
  File "C:\OnlyOnMyPC\udemy-dl\udemy\_colorized\colors.py", line 25, in <module>
    from colorama import init,Fore,Back,Style
ModuleNotFoundError: No module named 'colorama'
```

How to resolve this issue? Not, I installed the module and I am running Python 3.7.2

Thanks
Ameya Agashe

**Comment by devprojectid** [comment]
im not installed the module to, im using python 2 and 3, try using python3 udemy-dl.py
![Desktop screenshot (1)](https://user-images.githubusercontent.com/20605020/55286550-8ec32480-53cf-11e9-850c-2cea926d1937.png)
im using cookie not user pass.

**Comment by r0oth3x49** [comment]
@ameyaagashe you should install the requirements 1st.
`sudo pip install -r requirements.txt`
