### ISSUE TITLE
Download did not work with cookie.txt

### ISSUE THREAD

**Issue by ds2k5** [r0oth3x49/udemy-dl#373]
Hello,
got the cookie.txt link in the docu.
One Download of a course works fine.
Wanna download the next course and it fail:

[*] : Downloading course information .. -Traceback (most recent call last):
  File "./udemy-dl.py", line 1443, in <module>
    main()
  File "./udemy-dl.py", line 1102, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "./udemy-dl.py", line 436, in course_download
    course = udemy.course(url=self.url, username=self.username, password=self.password, cookies=self.cookies)
  File "/home/t0m/udemy-dl/udemy/_udemy.py", line 38, in course
    return Udemy(url, username, password, cookies, basic, callback)
  File "/home/t0m/udemy-dl/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/home/t0m/udemy-dl/udemy/_shared.py", line 62, in __init__
    self._fetch_course()
  File "/home/t0m/udemy-dl/udemy/_internal.py", line 56, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "/home/t0m/udemy-dl/udemy/_extract.py", line 584, in _real_extract
    'subtitles' : self._extract_subtitles(tracks),
  File "/home/t0m/udemy-dl/udemy/_extract.py", line 382, in _extract_subtitles
    lang = track.get('language') or track.get('srclang') or track.get('label') or track['locale'].get('locale').split('_')[0]
KeyError: 'locale'

**Comment by ds2k5** [comment]
after some other download try....

[*] : Trying to login using cookies ...
[+] : Logged in successfully.
[-] : Udemy Says : 403 Forbidden You do not have permission to perform this action. ...

**Comment by brundidge** [comment]
You're using old version. Clone again.

**Comment by ds2k5** [comment]
Thank you brundidge
that solved it!
