### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by hitsum** [r0oth3x49/udemy-dl#388]
Hi,

After taking the latest pull,

1.  I get forbidden error.
2.  Tried to copy the headers in a text file and uses the cookies method, I get following error:

[*] : Trying to login using cookies ...
Traceback (most recent call last):
  File "udemy-dl.py", line 1432, in <module>
    main()
  File "udemy-dl.py", line 1091, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 425, in course_download
    course = udemy.course(url=self.url, username=self.username, password=self.password, cookies=self.cookies)
  File "D:\downloads\udemy-downloader\test\udemy-dl-master\udemy\_udemy.py", line 38, in course
    return Udemy(url, username, password, cookies, basic, callback)
  File "D:\downloads\udemy-downloader\test\udemy-dl-master\udemy\_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "D:\downloads\udemy-downloader\test\udemy-dl-master\udemy\_shared.py", line 63, in __init__
    self._fetch_course()
  File "D:\downloads\udemy-downloader\test\udemy-dl-master\udemy\_internal.py", line 52, in _fetch_course
    auth = self._login(cookies=self._cookies)
  File "D:\downloads\udemy-downloader\test\udemy-dl-master\udemy\_extract.py", line 100, in _login
    self._cookies = self._extract_cookie_string(raw_cookies=cookies)
  File "D:\downloads\udemy-downloader\test\udemy-dl-master\udemy\_extract.py", line 87, in _extract_cookie_string
    cookies.update({'client_id': client_id.group('client_id'),
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by hitsum** [comment]
Hi,

Additional info:

I am running the following command -

python udemy-dl.py  https://www.udemy.com/hibernate-and-jpa-fundamentals -q 720 -k req-headers.txt

**Comment by 01ttouch** [comment]
open your cookie file and you can try add `[space]client_id=hello` (replace [space] with a space) at the end of it.

**Comment by 01ttouch** [comment]
i already fixed the problem login with username and password, you can download my fork here : https://github.com/01ttouch/udemy-dl/archive/json-decode-error.zip

**Comment by hitsum** [comment]
01ttouch,  Thanks a lot.  Resolved the issue.
