### ISSUE TITLE
udemy cookies

### ISSUE THREAD

**Issue by jaan143** [r0oth3x49/udemy-dl#398]
your new method is very easy but its not working on my side giving this error

[*] : Trying to login using cookies ...
Traceback (most recent call last):
  File "udemy-dl.py", line 1432, in <module>
    main()
  File "udemy-dl.py", line 1087, in main
    udemy.course_download(skip_captions=options.skip_captions, path=options.output, quality=options.quality, unsafe=opti
ons.unsafe)
  File "udemy-dl.py", line 425, in course_download
    course = udemy.course(url=self.url, username=self.username, password=self.password, cookies=self.cookies)
  File "C:\Users\HDNLRG\udemy\_udemy.py", line 38, in course
    return Udemy(url, username, password, cookies, basic, callback)
  File "C:\Users\HDNLRG\udemy\_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "C:\Users\HDNLRG\udemy\_shared.py", line 63, in __init__
    self._fetch_course()
  File "C:\Users\HDNLRG\udemy\_internal.py", line 52, in _fetch_course
    auth = self._login(cookies=self._cookies)
  File "C:\Users\HDNLRG\udemy\_extract.py", line 100, in _login
    self._cookies = self._extract_cookie_string(raw_cookies=cookies)
  File "C:\Users\HDNLRG\udemy\_extract.py", line 87, in _extract_cookie_string
    cookies.update({'client_id': client_id.group('client_id'),
AttributeError: 'NoneType' object has no attribute 'group'
PS C:\Users\HDNLRG>

here is screenshot but i edit value for screenshot because of security issue
![(1)](https://user-images.githubusercontent.com/15013833/58258043-71855380-7d8b-11e9-95c0-450f7db845fb.jpg)

**Comment by 01ttouch** [comment]
Your udemy-dl is old.
You can use command : `git pull` to get the lastest version of udemy-dl

**Comment by jaan143** [comment]
@01ttouch  bro i am sorry to disturb you
its working fine now 
i am closing this topic

**Comment by jaan143** [comment]
@01ttouch  will you give me your email i need your help 
i want to discuss you for a project
thanks
