### ISSUE TITLE
UnboundLocalError: 'chap' referenced before assignment.

### ISSUE THREAD

**Issue by dschaper** [r0oth3x49/udemy-dl#4]
Created a virtualenvironment with Python 2.7 as the interpreter. Added required via `pip install -r requirements.txt`. Invoked script and received the following error: (Redacted private infromation)

```
python udemy-dl.py -u udemy@<email> -p <password> https://www.udemy.com/<coursename> -l

              __                               ____  
   __  ______/ /__  ____ ___  __  __      ____/ / /  
  / / / / __  / _ \/ __ `__ \/ / / /_____/ __  / /   
 / /_/ / /_/ /  __/ / / / / / /_/ /_____/ /_/ / /    
 \__,_/\__,_/\___/_/ /_/ /_/\__, /      \__,_/_/     
                           /____/
                                 Version : 0.1
                                 Author  : Nasir khan(r0ot h3x49)
                                 Visit   : https://github.com/r0oth3x49



[*] : Downloading webpage..
[*] : Extracting course information..
[*] : Downloading 'course'.
[*] : Trying to login as (udemy@email)...
[+] : Logged in successfully.
[*] : Downloading course information webpages ..
[*] : Found (55) lectures ...
[*] : Extracting (55/1) |=---------------------------------------| 1.82%                                 

Traceback (most recent call last):
  File "udemy-dl.py", line 481, in <module>
    main()
  File "udemy-dl.py", line 451, in main
    udemy.ListDown()
  File "udemy-dl.py", line 186, in ListDown
    videos_dict = extract_info.real_extract(self.url, course_name, course_path)
  File "/home/dschaper/venvs/udemy-dl/udemy/_extractor.py", line 355, in real_extract
    if lecture_id not in udemy_dict[chap]:
UnboundLocalError: local variable 'chap' referenced before assignment
```

**Comment by r0oth3x49** [comment]
@dschaper can you show me the link of course you are trying to download?

**Comment by r0oth3x49** [comment]
@dschaper let me know if you still face an error

**Comment by dschaper** [comment]
That fix seems to have resolved the problem. Thanks!
