### ISSUE TITLE
Error: Invalid URI

### ISSUE THREAD

**Issue by nblavoie** [r0oth3x49/udemy-dl#427]
Getting this error while trying to download a course. Tried the authentication process with cookies; same result. Here is the trace log of the error :

```
Chapter : 1 - Introduction
Video : 2 - Who go.x-mpegURL
Resolution : 1080p
Location : xxx
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Invalid URI "/assets/aaa/files/642102/13974180/2018-08-25_06-19-12-yyy/xxx.m3u8"
    at Request.init (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:273:31)
    at new Request (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:127:8)
    at request (/usr/local/lib/node_modules/udemy-dl/node_modules/request/index.js:53:10)
    at /usr/local/lib/node_modules/udemy-dl/lib/download.js:95:25
    at /usr/local/lib/node_modules/udemy-dl/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:154:5)
Emitted 'error' event at:
    at Request.init (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:273:17)
    at new Request (/usr/local/lib/node_modules/udemy-dl/node_modules/request/request.js:127:8)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:154:5)
```

**Comment by r0oth3x49** [comment]
@nblavoie this issue is not related to this repo bro.
