### ISSUE TITLE
Downloading of an asset raises an error.

### ISSUE THREAD

**Issue by wkremser** [r0oth3x49/udemy-dl#428]
i just updated my udemy-dl hoping that this would fix the download problems. Now i ran into an new one.

Downloading of an asset (zip file) produces a stack trace.

Course i tried it with: https://www.udemy.com/react-native-the-practical-guide

Output inclusive stack trace:

[*] : Lecture(s) : (3 of 24)
[*] : Downloading (017 Setting Up A New Project)
[*] : Lecture : '017 Setting Up A New Project' (already downloaded).

[*] : Downloading subtitle(s)
[*] : Downloading (017 Setting Up A New Project-en)
[*] : 3.79KB/3.79KB 100.00% |##############################| 16.11kB/s
[+] : Downloaded  (017 Setting Up A New Project-en)

[*] : Downloading subtitle(s)
[*] : Downloading (017 Setting Up A New Project-it)
[*] : 3.98KB/3.98KB 100.00% |##############################| 12.95kB/s
[+] : Downloaded  (017 Setting Up A New Project-it)

[*] : Downloading subtitle(s)
[*] : Downloading (017 Setting Up A New Project-pl)
[*] : 4.10KB/4.10KB 100.00% |##############################| 14.84kB/s
[+] : Downloaded  (017 Setting Up A New Project-pl)

[*] : Downloading subtitle(s)
[*] : Downloading (017 Setting Up A New Project-pt)
[*] : 4.12KB/4.12KB 100.00% |##############################| 16.64kB/s
[+] : Downloaded  (017 Setting Up A New Project-pt)

[*] : Downloading asset(s)
[*] : Downloading (017 basics-01-starting-project.zip)
Traceback (most recent call last):
  File "/home/wkremser/Projects/udemy-dl/udemy-dl.py", line 1432, in <module>
    main()
  File "/home/wkremser/Projects/udemy-dl/udemy-dl.py", line 1091, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "/home/wkremser/Projects/udemy-dl/udemy-dl.py", line 500, in course_download
    self.download_lectures_and_captions(lecture_best=lecture_best, lecture_title=lecture_title, inner_index=inner_index, lectures_count=lectures_count, lecture_subtitles=lecture_subtitles, lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
  File "/home/wkremser/Projects/udemy-dl/udemy-dl.py", line 418, in download_lectures_and_captions
    self.download_assets(lecture_assets=lecture_assets, filepath=filepath, unsafe=unsafe)
  File "/home/wkremser/Projects/udemy-dl/udemy-dl.py", line 332, in download_assets
    retval = assets.download(filepath=filepath, unsafe=unsafe, quiet=True, callback=self.show_progress)
AttributeError: 'InternUdemyLectureAssets' object has no attribute 'download'

**Comment by wkremser** [comment]
Might have found it ..

in _shared.py i changed at Line 508

**from:**
class UdemyLectureAssets(object):


**to:**
class UdemyLectureAssets(Downloader):

now it seems to work :)
