### ISSUE TITLE
TypeError: unbound method __init__() must be called with Downloader instance as first argument (got InternUdemyLectureAssets instance instead)

### ISSUE THREAD

**Issue by EnoqueEsteves** [r0oth3x49/udemy-dl#429]
This has only recently started to happen when using the `udemy-dl.py` to download a course.  This happens on both an update to an already downloaded course as well as downloading a new one. 

```
Traceback (most recent call last):
  File "./udemy-dl.py", line 1432, in <module>
    main()
  File "./udemy-dl.py", line 1091, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "./udemy-dl.py", line 467, in course_download
    lecture_assets = lecture.assets
  File "/mnt/g/udemy-downloader/udemy-dl/udemy/_shared.py", line 341, in assets
    self._process_assets()
  File "/mnt/g/udemy-downloader/udemy-dl/udemy/_internal.py", line 119, in _process_assets
    assets  =   [InternUdemyLectureAssets(z, self) for z in self._info['assets']] if self._assets_count > 0 else []
  File "/mnt/g/udemy-downloader/udemy-dl/udemy/_internal.py", line 143, in __init__
    super(InternUdemyLectureAssets, self).__init__(parent)
  File "/mnt/g/udemy-downloader/udemy-dl/udemy/_shared.py", line 521, in __init__
    Downloader.__init__(self)
TypeError: unbound method __init__() must be called with Downloader instance as first argument (got InternUdemyLectureAssets instance instead)
```

**Comment by r0oth3x49** [comment]
@EnoqueEsteves can you please follow the issue reporting template?

**Comment by EnoqueEsteves** [comment]
@r0oth3x49 - apologies I have updated the issue following you template. Let us know if you require any further information or clarification.
