### ISSUE TITLE
Error downloading course

### ISSUE THREAD

**Issue by faizanbashir** [r0oth3x49/udemy-dl#435]
**TypeError: 'NoneType' object is not iterable**
I am getting above error after successfully logging into udemy, unable to download course.

**To Reproduce**
1. Course url: [`https://www.udemy.com/course/certified-kubernetes-application-developer/`] 'Kubernetes Certified Application Developer (CKAD) with Tests'
2. Command: `python udemy-dl.py certified-kubernetes-application-developer`
3. Stack trace:
`[+] : Logged in successfully.

Traceback (most recent call last):on ..
  File "udemy-dl.py", line 1432, in <module>
    main()
  File "udemy-dl.py", line 1271, in main
    udemy.course_download(path=options.output, quality=options.quality, unsafe=options.unsafe)
  File "udemy-dl.py", line 425, in course_download
    course = udemy.course(url=self.url, username=self.username, password=self.password, cookies=self.cookies)
  File "/Users/faizanbashir/udemy-dl/udemy/_udemy.py", line 38, in course
    return Udemy(url, username, password, cookies, basic, callback)
  File "/Users/faizanbashir/udemy-dl/udemy/_internal.py", line 44, in __init__
    super(InternUdemyCourse, self).__init__(*args, **kwargs)
  File "/Users/faizanbashir/udemy-dl/udemy/_shared.py", line 219, in __init__
    self._fetch_course()
  File "/Users/faizanbashir/udemy-dl/udemy/_internal.py", line 56, in _fetch_course
    self._info              =       self._real_extract(self._url)
  File "/Users/faizanbashir/udemy-dl/udemy/_extract.py", line 442, in _real_extract
    course_id, course_info = self._extract_course_info(url)
  File "/Users/faizanbashir/udemy-dl/udemy/_extract.py", line 187, in _extract_course_info
    portal_name, course_name = self._course_name(url)
TypeError: 'NoneType' object is not iterable`

**Python Environment:**
 - OS Platform: [macOS Mojave]
 - Python Version [e.g. 2.7.10]

**Comment by r0oth3x49** [comment]
@faizanbashir the command you are using is wrong you should provide complete url instead.

proper command should be.
`python udemy-dl.py https://www.udemy.com/course/certified-kubernetes-application-developer/`
