### ISSUE TITLE
[Resolved] Error while running script

### ISSUE THREAD

**Issue by undeinf** [r0oth3x49/udemy-dl#442]
Please help on below error:

Traceback (most recent call last):
  File "udemy-dl.py", line 7, in <module>
    import udemy
  File "D:\udemy_dl\udemy-dl-master\udemy\__init__.py", line 32, in <module>
    from ._udemy import course
  File "D:\udemy_dl\udemy-dl-master\udemy\_udemy.py", line 26, in <module>
    from ._internal import InternUdemyCourse as Udemy
  File "D:\udemy_dl\udemy-dl-master\udemy\_internal.py", line 30, in <module>
    from ._extract import Udemy
  File "D:\udemy_dl\udemy-dl-master\udemy\_extract.py", line 50, in <module>
    from ._sanitize import (
  File "D:\udemy_dl\udemy-dl-master\udemy\_sanitize.py", line 10, in <module>
    from unidecode import unidecode
ModuleNotFoundError: No module named 'unidecode'

python intalled : 3.7.3

command:

python udemy-dl.py COURSE_URL -k token.txt -o e:/udemy --unsafe

thanks

**Comment by undeinf** [comment]
Error with unidecode module, I've installed and it is working.

Kindly delete this thread!
