### ISSUE TITLE
Udemy-dl can't download

### ISSUE THREAD

**Issue by princebillyGK** [r0oth3x49/udemy-dl#462]
I am getting this error
[INFO-835] Downloading to: /home/princebillygk/course

[INFO-107] Trying to log in ...
Traceback (most recent call last):
  File "/usr/local/bin/udemy-dl", line 7, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 658, in udemy_dl
    login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 109, in login
    csrf_token = get_csrf_token()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 102, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Python Environment **
ubuntu 19.04
python3

**Comment by r0oth3x49** [comment]
@princebillyGK clone this repository and then try to download the course if some error then let me know
