### ISSUE TITLE
Unable to download the Udemy Video using udemy-dl 

### ISSUE THREAD

**Issue by infotovikas** [r0oth3x49/udemy-dl#467]
**Describe the bug**

**To Reproduce**
1. udemy course url: https://www.udemy.com/course/build-an-app-with-aspnet-core-and-angular-from-scratch/learn/lecture/8707124#overview
2. Run the following command to reproduce the error.
python udemy-dl.py https://www.udemy.com/course/build-an-app-with-aspnet-core-and-angular-from-scratch/learn/lecture/8707124#overview
3. See error

[-] Unable to extract login-form form
Traceback (most recent call last):
  File "udemy-dl.py", line 924, in <module>
    main()
  File "udemy-dl.py", line 713, in main
    udemy.ExtractAndDownload()
  File "udemy-dl.py", line 291, in ExtractAndDownload
    self.login()
  File "udemy-dl.py", line 40, in login
    extract_info.login(self.username, self.password)
  File "D:\Python\udemy-dl-master\udemy-dl-master\udemy\_extractor.py", line 184
, in login
    login_form      = self._fill_login_form(login_popup, username, password)
  File "D:\Python\udemy-dl-master\udemy-dl-master\udemy\_extractor.py", line 135
, in _fill_login_form
    login_form = self._form_hidden_inputs('login-form', webpage)
  File "D:\Python\udemy-dl-master\udemy-dl-master\udemy\_extractor.py", line 125
, in _form_hidden_inputs
    return _hidden_inputs(form)
  File "D:\Python\udemy-dl-master\udemy-dl-master\udemy\_utils.py", line 79, in
_hidden_inputs
    html = re.sub(r'', '', html)
  File "C:\Users\Aarav Singh\AppData\Local\Programs\Python\Python36\lib\re.py",
line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
![error](https://user-images.githubusercontent.com/19883781/72755607-e8ac0980-3bf0-11ea-98fd-58f86d9811dd.png)

**Screenshots**

**Python Environment (please complete the following information):**
 - OS Platform: [e.g. Windows 8.1]
 - Python Version [3.6.2]

**Additional context**

**Comment by r0oth3x49** [comment]
try using cookie based method instead i can't reproduce this error for me it works fine, also try upgrading to latest stable python version. i have tried with python 3.7
