### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by KindlyFire** [r0oth3x49/udemy-dl#47]
I have the following error: 

```
[*] : Downloading lecture : (2 of 16)
[*] : Downloading (048 Dexterity Exercise 2 - Ninja Fretting Hand Skills-subtitle-en.vtt)
Traceback (most recent call last):
  File "udemy-dl.py", line 898, in <module>
    main()
  File "udemy-dl.py", line 828, in main
    udemy.ExtractAndDownload(path=outto, quality=res, default=True)
  File "udemy-dl.py", line 396, in ExtractAndDownload
    out = self.Downloader(_url, lecture_name, chapter_path)
  File "udemy-dl.py", line 88, in Downloader
    out = course_dl.download(url, title, filepath=path, quiet=True, callback=self.Download)
  File "/home/anon/Apps/udemy-dl/udemy/_downloader.py", line 115, in download
    eta  = (total - bytesdone) / (rate * 1024.0)
ZeroDivisionError: float division by zero
```

While downloading [this course](https://www.udemy.com/complete-guitar-system-beginner-to-advanced/learn/v4/overview).

**Comment by r0oth3x49** [comment]
@KindlyFire thank you for the report. Actually i don't have this particular course in my account so i cannot test against this course that's why i am suggesting you to use `--skip-sub` command to download the whole course and then use the `--sub-only` to download subtitles.
