### ISSUE TITLE
Unable to download paid video on Udemy

### ISSUE THREAD

**Issue by infotovikas** [r0oth3x49/udemy-dl#49]
Getting Below error

Traceback (most recent call last):
  File "udemy-dl.py", line 915, in <module>
    main()
  File "udemy-dl.py", line 705, in main
    udemy.ExtractAndDownload()
  File "udemy-dl.py", line 411, in ExtractAndDownload
    _is_converted = vtt2srt.convert(lecture_name)
  File "D:\Python\Software\udemy-dl-master\udemy-dl-master\udemy\_utils.py", line 227, in convert
    content     =   [line for line in (l.strip() for l in f_in) if line]
  File "D:\Python\Software\udemy-dl-master\udemy-dl-master\udemy\_utils.py", line 227, in <listcomp>
    content     =   [line for line in (l.strip() for l in f_in) if line]
  File "D:\Python\Software\udemy-dl-master\udemy-dl-master\udemy\_utils.py", line 227, in <genexpr>
    content     =   [line for line in (l.strip() for l in f_in) if line]
  File "D:\Users\vikas_sing\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 40: character maps to <undefined>

**Comment by r0oth3x49** [comment]
@infotovikas thanks for the report. need a bit explanation.
if you don't mind can you share the course URL? which OS you are using in WIN7 or what?

**Comment by infotovikas** [comment]
@r0oth3x49 yes sure, https://www.udemy.com/the-complete-guide-to-angular-2/learn/v4/content and I am using window 10 OS.

**Comment by r0oth3x49** [comment]
@infotovikas i have added a fix and tested with `Python 3.6.2` on `Windows 10` and it worked well. try now and let me if you still face the error.

**Comment by infotovikas** [comment]
Great!! thanks, let me check and validate the same!!
