### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by v4animesh** [r0oth3x49/udemy-dl#492]
Getting the below error:

Traceback (most recent call last):
  File "udemy-dl.py", line 7, in <module>
    import udemy
  File "C:\Users\Animesh\udemy\__init__.py", line 32, in <module>
    from ._udemy import course
  File "C:\Users\Animesh\udemy\_udemy.py", line 26, in <module>
    from ._internal import InternUdemyCourse as Udemy
  File "C:\Users\Animesh\udemy\_internal.py", line 29, in <module>
    from ._colorized import *
  File "C:\Users\Animesh\udemy\_colorized\__init__.py", line 25, in <module>
    from .colors import *
  File "C:\Users\Animesh\udemy\_colorized\colors.py", line 25, in <module>
    from colorama import init,Fore,Back,Style
ModuleNotFoundError: No module named 'colorama'

**Comment by Taranis01** [comment]
install requirements

**Comment by v4animesh** [comment]
I have installed that as well..
Still not working.

**Comment by Taranis01** [comment]
hm, did you install it at the same python environment that you are using to start the script? And same python version?

**Comment by v4animesh** [comment]
Thanks for the reply.
I am now able to run it till the point userid and pw is asked. 
There after I am getting "Failed to login"

**Comment by v4animesh** [comment]
Thank you so much.
It is working fine now.
