### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 3574: invalid start byte

### ISSUE THREAD

**Issue by elevenrax** [r0oth3x49/udemy-dl#52]
In downloading this course:
https://goo.gl/npcfo3

Module 01 - Getting started with docker technologies 
Downloads fine.

However, when it goes to start module 02 - Working with docker images.
I get the following error:

```
Traceback (most recent call last):
  File "udemy-dl.py", line 915, in <module>
    main()
  File "udemy-dl.py", line 705, in main
    udemy.ExtractAndDownload()
  File "udemy-dl.py", line 411, in ExtractAndDownload
    _is_converted = vtt2srt.convert(lecture_name)
  File "/Users/mememe/UdemyDownloader/udemy-dl/udemy/_utils.py", line 227, in convert
    content     =   [line for line in (l.strip() for l in f_in) if line]
  File "/Users/mememe/UdemyDownloader/udemy-dl/udemy/_utils.py", line 227, in <listcomp>
    content     =   [line for line in (l.strip() for l in f_in) if line]
  File "/Users/mememe/UdemyDownloader/udemy-dl/udemy/_utils.py", line 227, in <genexpr>
    content     =   [line for line in (l.strip() for l in f_in) if line]
  File "/Users/mememe/anaconda/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 3574: invalid start byte
```

Using MacOS with Python 3.5. 

Running:
 
`pip install -r requirements.txt`

Confirms that all requirements are already satisfied.

**Comment by r0oth3x49** [comment]
@elevenrax thanks for the report. i will try to reproduce fix ASAP.

**Comment by elevenrax** [comment]
Many thanks :)

**Comment by csetarun** [comment]
Got this error

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 2: invalid start byte

```
File "/home/pvanaparthi/udemy-dl/udemy/_vtt2srt.py", line 45, in <genexpr>
content = [line for line in (l.strip() for l in f)]
```
replacing this 
`f = codecs.open(filename=fname, encoding='utf-8')`
with this resolved the issue.
`f = open(filename=fname, encoding='utf-8')`
