### ISSUE TITLE
Loading bar Problem

### ISSUE THREAD

**Issue by coozgan** [r0oth3x49/udemy-dl#53]
Hey bro, I have this problem. I dont know what seems to be the problem, I run it for python 2.7, please take a look at this

```
Traceback (most recent call last):
  File "udemy-dl.py", line 918, in <module>
    main()
  File "udemy-dl.py", line 591, in main
    udemy.ExtractAndDownload()
  File "udemy-dl.py", line 409, in ExtractAndDownload
    msg = self.Downloader(_url, lecture_name, chapter_path)
  File "udemy-dl.py", line 89, in Downloader
    out = course_dl.download(url, title, filepath=path, quiet=True, callback=self.Download)
  File "C:\Users\Medica-Joshua\Desktop\udemy-dl\udemy\_downloader.py", line 153, in download
    callback(total, *progress_stats)
  File "udemy-dl.py", line 86, in Download
    self.Progress(Receiving, TotalSize, fileSize = str(Size) + str(SGb_SMb) , downloaded = str(Received) + str(RGb_RMb), rate = str(dls) + str(Mb_kB), suffix = str(eta), barLength = 40)
  File "udemy-dl.py", line 49, in Progress
    stdout.write('{}{}[{}{}*{}{}] : {}{}{}/{} {}% |{}{}{}| {} {}s ETA                                \r'.format(fc,sd,fm,sb,fc,sd,fg,sb,fileSize,downloaded,percents,bar,fg,sb,rate,suffix))
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Python27\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
IOError: [Errno 0] Error
```

**Comment by r0oth3x49** [comment]
@coozgan can you please explain a bit? which course you are trying to download and etc..?
