### ISSUE TITLE
Udemy-dl v1.0 execution errors

### ISSUE THREAD

**Issue by SpecieX** [r0oth3x49/udemy-dl#551]
Greetings, 

I've just downloaded the v1.0 release and when I try to execute 
the command "python .\udemy-dl.py", it doesn't work and show some errors:

Traceback (most recent call last):
  File ".\udemy-dl.py", line 31, in <module>
    import udemy
  File "C:\udemy-dl-1.0\udemy\__init__.py", line 32, in <module>
    from udemy.udemy import course, fetch_enrolled_courses
  File "C:\udemy-dl-1.0\udemy\udemy.py", line 27, in <module>
    from udemy.internal import InternUdemyCourse as Udemy
  File "C:\udemy-dl-1.0\udemy\internal.py", line 26, in <module>
    from udemy.compat import time, sys
  File "C:\udemy-dl-1.0\udemy\compat.py", line 33, in <module>
    import m3u8
ModuleNotFoundError: No module named 'm3u8'

Thank you.

**Comment by caleb-tolu** [comment]
You need to run this again `pip install -r requirements.txt`

**Comment by SpecieX** [comment]
> 
> 
> You need to run this again `pip install -r requirements.txt`

Oh! My bad!

Now it works flawlessly!

Thank you caleb-tolu
