### ISSUE TITLE
Error when trying to download course

### ISSUE THREAD

**Issue by jrdnbrn** [r0oth3x49/udemy-dl#61]
I get this error when trying to download a course

```
Traceback (most recent call last):
  File "udemy-dl.py", line 924, in <module>
    main()
  File "udemy-dl.py", line 856, in main
    udemy.ExtractAndDownload(path=outto, quality=res)
  File "udemy-dl.py", line 409, in ExtractAndDownload
    msg = self.Downloader(_url, lecture_name, chapter_path)
  File "udemy-dl.py", line 89, in Downloader
    out = course_dl.download(url, title, filepath=path, quiet=True, callback=self.Download)
  File "C:\Users\Jordan Baron\Projects\udemy-dl\udemy\_downloader.py", line 101, in download
    outfh = open(temp_filepath, fmode)
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Jordan Baron\\Desktop\\NodeJS Udemy Course"\\the-complete-nodejs-developer-course-2\\01 Welcome.part'
```

The command I use is as follows, I removed my credentials for obvious reasons. 

`python udemy-dl.py -u EMAIL/USERNAME -p PASSWORD https://www.udemy.com/the-complete-nodejs-developer-course-2/learn/v4/overview -r 720 -o "C:\Users\Jordan Baron\Desktop\NodeJS Udemy Course\"`

**Comment by r0oth3x49** [comment]
@jrdnbrn don't use `\` at end of path where you want to save your course. and one more thing i would suggest not to use spaces in directory name.

try this command.
```
python udemy-dl.py -u EMAIL/USERNAME -p PASSWORD https://www.udemy.com/the-complete-nodejs-developer-course-2/learn/v4/overview -r 720 -o "E:\udemy\courses"
```
OR

```
python udemy-dl.py -u EMAIL/USERNAME -p PASSWORD https://www.udemy.com/the-complete-nodejs-developer-course-2/learn/v4/overview -r 720 -o "C:\Users\Jordan Baron\Desktop\NodeJS Udemy Course"
```

**Comment by jrdnbrn** [comment]
Apparently I'm 'not enrolled' which is false...
