### ISSUE TITLE
MacOS bug?

### ISSUE THREAD

**Issue by Ropuh** [r0oth3x49/udemy-dl#622]
`rob@Mac-Rob` udemy-dl-master % ./udemy-dl.py https://www.udemy.com/course/...something.../ --cookie=cookie.txt
Traceback (most recent call last):

  File "./udemy-dl.py", line 31, in <module>
    import udemy

  File "/Users/rob/Downloads/udemy-dl-master/udemy/__init__.py", line 32, in <module>
    from udemy.udemy import course, fetch_enrolled_courses

  File "/Users/rob/Downloads/udemy-dl-master/udemy/udemy.py", line 27, in <module>
    from udemy.internal import InternUdemyCourse as Udemy

  File "/Users/rob/Downloads/udemy-dl-master/udemy/internal.py", line 26, in <module>
    from udemy.compat import time, sys

  File "/Users/rob/Downloads/udemy-dl-master/udemy/compat.py", line 33, in <module>
    import m3u8

ModuleNotFoundError: No module named 'm3u8'

rob@Mac-Rob udemy-dl-master % pip3 install m3u8

Requirement already satisfied: m3u8 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.8.0)

Requirement already satisfied: iso8601 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from m3u8) (0.1.14)

rob@Mac-Rob udemy-dl-master % 
`

MacOS / BigSur / AppleSilicon / Python 3.9.2

**Comment by dokumanx** [comment]
Same error here

**Comment by r0oth3x49** [comment]
you guys should install the lib for same python version which is used while you run udemy-dl.
