### ISSUE TITLE
error in [ python udemy-dl.py https://www.udemy.com/course/rest-api-python-y-django/ ]

### ISSUE THREAD

**Issue by llimpeo** [r0oth3x49/udemy-dl#626]
error.

pppp@pppp MINGW64 /e/udemy/udemy-dl (master)
$ python --version
Python 3.8.2

ppppp@pppp MINGW64 /e/udemy/udemy-dl (master)
$ python udemy-dl.py https://www.udemy.com/course/rest-api-python-y-django/
Traceback (most recent call last):
  File "udemy-dl.py", line 31, in <module>
    import udemy
  File "E:\udemy\udemy-dl\udemy\__init__.py", line 32, in <module>
    from udemy.udemy import course, fetch_enrolled_courses
  File "E:\udemy\udemy-dl\udemy\udemy.py", line 27, in <module>
    from udemy.internal import InternUdemyCourse as Udemy
  File "E:\udemy\udemy-dl\udemy\internal.py", line 26, in <module>
    from udemy.compat import time, sys
  File "E:\udemy\udemy-dl\udemy\compat.py", line 33, in <module>
    import m3u8
ModuleNotFoundError: No module named 'm3u8'

pppp@pppp MINGW64 /e/udemy/udemy-dl (master)

**Comment by r0oth3x49** [comment]
@llimpeo did you managed to install the requirements? If not you should be installing it first before running the code
