### ISSUE TITLE
issue in downloading udemy courses using node.js

### ISSUE THREAD

**Issue by bala93kumar** [r0oth3x49/udemy-dl#79]
i tried the below command to download udemy courses using node.js on windows 10  and i am  face facing the error as mentioned below please assist 

udl -u xxxxxx  -p xxxxxxxx   https://www.udemy.com/the-docker-for-devops-course-from-development-to-production/learn/v4/content -o "E:\Udemy\The Docker for DevOps course From development to production"

              _                                          _   _
 _   _    __| |   ___   _ __ ___    _   _            __| | | |
 | | | |  / _` |  / _ \ | '_ ` _ \  | | | |  _____   / _` | | |
 | |_| | | (_| | |  __/ | | | | | | | |_| | |_____| | (_| | | |
  \__,_|  \__,_|  \___| |_| |_| |_|  \__, |          \__,_| |_|
                                     |___/
C:\Users\Ramkumar\AppData\Roaming\npm\node_modules\udemy-dl\lib\core.js:356
      var course_data_len = course_data['results'].length;
                                                   ^

TypeError: Cannot read property 'length' of undefined
    at Request._callback (C:\Users\Ramkumar\AppData\Roaming\npm\node_modules\udemy-dl\lib\core.js:356:52)
    at Request.self.callback (C:\Users\Ramkumar\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (C:\Users\Ramkumar\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (C:\Users\Ramkumar\AppData\Roaming\npm\node_modules\udemy-dl\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)

**Comment by bala93kumar** [comment]
if you don't know how to answer my question , mention that you don't know , do not close the issue

**Comment by r0oth3x49** [comment]
@bala93kumar you should have a look first before reporting an issue on a `repo` whether it is related or not.
