### ISSUE TITLE
ImportError Thrown When trying to download

### ISSUE THREAD

**Issue by IsraelGboluwaga** [r0oth3x49/udemy-dl#91]
```
Traceback (most recent call last):
  File "udemy-dl.py", line 7, in <module>
    import udemy
  File "/Users/israel.arunah/Documents/udemy-dl/udemy-dl/udemy/__init__.py", line 6, in <module>
    from 	._downloader 	import Downloader
  File "/Users/israel.arunah/Documents/udemy-dl/udemy-dl/udemy/_downloader.py", line 8, in <module>
    from .colorized import *
  File "/Users/israel.arunah/Documents/udemy-dl/udemy-dl/udemy/colorized/__init__.py", line 1, in <module>
    from .Output import *
  File "/Users/israel.arunah/Documents/udemy-dl/udemy-dl/udemy/colorized/Output.py", line 1, in <module>
    from colorama import init,Fore,Back,Style
ImportError: No module named colorama

```

**Comment by r0oth3x49** [comment]
@IsraelGboluwaga you should install the requirements first.

**Comment by IsraelGboluwaga** [comment]
It's worked. Thanks.

If I may ask, what caused the sudden loss of requirements because I used to download stuff without issues before?

**Comment by r0oth3x49** [comment]
@IsraelGboluwaga  what can i say about python installation in your PC.

**Comment by IsraelGboluwaga** [comment]
I've been using it before. And I use a mac, which means python is pre-installed on my system. I was wondering why it stopped all of a sudden.

**Comment by r0oth3x49** [comment]
@IsraelGboluwaga the above error simply shows that you don't have colorama installed so that can be the reason.
